# permissions for end users to view distributetrainjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributetrainjob-viewer-role
rules:
- apiGroups:
  - sugar.sugar.com
  resources:
  - distributetrainjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sugar.sugar.com
  resources:
  - distributetrainjobs/status
  verbs:
  - get
